[package]
name = "parquet_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "54.0.0"
parquet = { version="54.0.0", features=["async"] }
base = { path = "../base" }
async-trait = "0.1.51"
futures = "0.3.31"
tokio = { version = "1.16.1", features = ["full"] }